[package]
name = "my-prompt"
version = "0.0.3"
edition = "2024"
authors = ["Chris Becker <chris@becker.am>"]
description = "My ultra-fast shell prompt based on `prmt` by Ivan Zakharchanka"
license = "MIT"
repository = "https://github.com/cbeck527/my-prompt"
homepage = "https://github.com/cbeck527/my-prompt"
readme = "README.md"
keywords = ["prompt", "shell", "terminal", "cli", "performance"]
categories = ["command-line-utilities", "command-line-interface"]

[lib]
name = "my_prompt"
path = "src/lib.rs"

[[bin]]
name = "my-prompt"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive", "env"] }
gix = { version = "0.73", default-features = false, features = ["max-performance-safe", "status", "revision"] }
rayon = "1"
dirs = "6"
thiserror = "2"
anyhow = "1"
bitflags = "2"
chrono = "0.4"
whoami = "1.6.1"
serde_json = "1.0.145"
serde = { version = "1.0.228", features = ["derive"] }
git2 = { version = "0.20.2", features = ["vendored-libgit2", "vendored-openssl"] }

[dev-dependencies]
criterion = { version = "0.7", features = ["html_reports"] }
regex = "1"
serial_test = "3"
tempfile = "3"

[lints.clippy]
pedantic = { level = "deny", priority = -1 }

[lints.rust]
warnings = "deny"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
strip = true
panic = "abort"
overflow-checks = false

[profile.release.build-override]
opt-level = 0
codegen-units = 16
